### ISSUE TITLE
Environment upgrade command

### ISSUE THREAD

**Issue by evghen1** [kndpio/cli#143]
### What problem are you facing?
After new features comes to KNDP related to environment currently is not possible to use it until environment recreated.

### How could KNDP help solve your problem?
Add `kndp env upgrade` command which will not create new cluster, but just execute install of engine.

**Comment by ca7alindev** [comment]
@evghen1 additional parameter for context will be required? Or engine will be installed by default in current cluster context?

**Comment by evghen1** [comment]
Yes, required
