### ISSUE TITLE
Basic structure of TUI version for KNDP CLI application

### ISSUE THREAD

**Issue by evghen7** [kndpio/cli#23]
## Goal
Update KNDP CLI architecture to incorporate the Charm Bubbletea TUI framework. This will enable an interactive TUI where users can access existing CLI commands by UI.

## Key Points
- **Maintain CLI Commands:** Preserve all current CLI functionalities.
- **Bubbletea Integration:** Embed Bubbletea TUI to introduce an interactive layer for command execution.

## Todo
1. Integrate Bubbletea TUI without altering current CLI commands.
2. Ensure new TUI layer allows interactive use of existing commands.
3. Make empty Bubbletea UI application ran on execution of `kndp` command without parameters.

## Outcome
Facilitate an enhanced user experience by providing an interactive interface for existing CLI functionalities, leveraging Bubbletea TUI.

**Comment by web7evgheni** [comment]
As main idea:
 - KNDP could have two move of executed CLI and TUI.
 - Using BubbleTea, possible to define TUI view for every command in TUI mode.
 - Command logic stored outside of view could be executed in different mode.
